import Link from "next/link";
import HostPrivatePage from "@/components/host/HostPrivatePage";
import { getPrivateHostData, type HostDashboard } from "@/lib/host";

const money = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;

export default async function HostDashboardPage({ searchParams }: { searchParams: Promise<{ setup?: string }> }) {
  const { setup } = await searchParams;
  return <HostPrivatePage path="/host-dashboard">{async profile => {
    const data = await getPrivateHostData<HostDashboard>("host/dashboard");
    if (!data) return <div className="host-empty"><h3>Host dashboard is unavailable</h3><p>Check that the updated WordPress Host API is installed, then refresh.</p></div>;
    return <>{setup === "logo" && <p className="host-notice" role="status">Your host account was created, but the logo did not upload. Add it from your public profile.</p>}<div className="host-toolbar"><div><span className="host-eyebrow">HOST CONTROL ROOM</span><h1 className="host-title">Run the crew.<br /><em>See the upside.</em></h1><p className="host-copy">Welcome back, {profile.name}. Your trips, travellers and money moves are all here.</p></div><Link className="host-button" href="/admin-host-trips">Build a trip <span>→</span></Link></div>
      <section className="host-grid four" aria-label="Host performance"><div className="host-card host-metric"><small>Live trips</small><strong>{data.stats.trips}</strong></div><div className="host-card host-metric"><small>Bookings</small><strong>{data.stats.bookings}</strong></div><div className="host-card host-metric"><small>Confirmed crew</small><strong>{data.stats.guests}</strong></div><div className="host-card host-metric"><small>Eligible earnings</small><strong>{money(data.stats.earnings)}</strong></div></section>
      <section className="host-section"><div className="host-section-head"><div><span className="host-eyebrow">RIGHT NOW</span><h2>Trip <em>snapshot.</em></h2></div></div><div className="host-grid"><div className="host-panel"><h3>Confirmed bookings</h3><strong style={{ fontSize: 28 }}>{data.stats.confirmed}</strong><p className="host-copy">Completed and fully paid bookings</p></div><div className="host-panel"><h3>Profit in pipeline</h3><strong style={{ fontSize: 28 }}>{money(data.stats.pipeline)}</strong><p className="host-copy">Subject to confirmation and adjustments</p></div><div className="host-panel"><h3>Payout destination</h3><strong>{data.payout_ready ? "Ready" : "Setup required"}</strong><p className="host-copy">{data.payout_ready ? "Your details are secured." : "Add a bank account or UPI ID before the next payout run."}</p><Link className="host-text-link" href="/host-payout-details">{data.payout_ready ? "View details" : "Finish setup"} →</Link></div></div></section>
      <section className="host-section"><div className="host-section-head"><div><span className="host-eyebrow">FAST MOVES</span><h2>What&apos;s <em>next?</em></h2></div></div><div className="host-grid four">{[["Build trips", "/admin-host-trips", "Pick a departure"], ["Drop a reel", "/host-reels", "Turn moments into bookings"], ["Open wallet", "/host-wallet", "Track money moves"], ["Meet the crew", "/host-customer-booking-history", "View traveller bookings"]].map(([title, href, caption]) => <Link key={href} className="host-panel" href={href}><strong>{title} →</strong><p className="host-copy">{caption}</p></Link>)}</div></section>
      <section className="host-section"><div className="host-section-head"><div><span className="host-eyebrow">RECENT CREW</span><h2>Latest <em>bookings.</em></h2></div><Link className="host-text-link" href="/host-customer-booking-history">See all →</Link></div>{data.recent_bookings.length ? <div className="host-table-wrap"><table className="host-table"><thead><tr><th>Booking</th><th>Traveller</th><th>Trip</th><th>Departure</th><th>Status</th></tr></thead><tbody>{data.recent_bookings.map(order => <tr key={order.id}><td>#{order.id}</td><td>{order.customer}</td><td>{order.tour_title}</td><td>{order.check_in || "TBA"}</td><td><span className="host-status">{order.status}</span></td></tr>)}</tbody></table></div> : <div className="host-empty"><h3>Your first booking lands here.</h3><p>Publish a trip, rally your people and start forming the crew.</p><Link className="host-button" href="/admin-host-trips">Explore host trips <span>→</span></Link></div>}</section>
    </>;
  }}</HostPrivatePage>;
}
