"use client";
import type { BookingEditorData } from "@/lib/admin-booking-editor-types";
import AdminBookingEditorModal from "./AdminBookingEditorModal";
import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent, type ReactNode } from "react";
import AdminMenu from "./AdminMenu";
import AdminBookingCharts from "./AdminBookingCharts";
import AdminBookingDetails from "./AdminBookingDetails";
import { BOOKING_COLUMNS, BOOKING_WIDTHS, MONTHS, bookingAnalytics, bookingMatches, bookingSummary, coordinatorMessage, money, type AdminBooking, type AdminBookingsData } from "@/lib/admin-bookings-types";
import "./admin-bookings-original.css";
import "./admin-bookings-native.css";
const PREFS = "tripanza-admin-booking-columns-v1";
const Icon = ({ name }: { name: string }) => <i aria-hidden="true" className={`fa-solid ${name}`} />;
const number = (value: number) => value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
function Trip({ row }: { row: AdminBooking }) { return <div className="tz-trip-cell"><a className="tz-trip-cell__title" href={row.trip_url} target="_blank" rel="noopener noreferrer">{row.title}</a><div className="tz-trip-cell__source"><span className={row.poster === "host" ? "is-host" : "is-direct"}>{row.source}</span>{row.host && row.source === "Host sale" && <strong>Sold by {row.host}</strong>}{row.owner && row.poster === "host" && <small>Trip owner: {row.owner} · Storefront #{row.storefront_id}</small>}<a href={row.inventory_url} target="_blank" rel="noopener noreferrer">Master #{row.inventory_id}</a></div></div>; }
export default function AdminBookings({ initial, wordpressOrigin }: { initial: AdminBookingsData; wordpressOrigin: string }) {
  const [data, setData] = useState(initial), [archive, setArchive] = useState(false);
  const [query, setQuery] = useState(""), [trip, setTrip] = useState(""), [status, setStatus] = useState(""), [poster, setPoster] = useState("");
  const [archiveQuery, setArchiveQuery] = useState(""), [archiveTrip, setArchiveTrip] = useState(""), [archiveStatus, setArchiveStatus] = useState(""), [archivePoster, setArchivePoster] = useState("");
  const [year, setYear] = useState(initial.today.slice(0, 4)), [month, setMonth] = useState("all");
  const [hidden, setHidden] = useState<number[]>([]), [widths, setWidths] = useState(BOOKING_WIDTHS);
  const [selected, setSelected] = useState<number[]>([]), [busy, setBusy] = useState<string[]>([]), [loading, setLoading] = useState(false);
  const [notice, setNotice] = useState<{ text: string; error: boolean } | null>(null), [details, setDetails] = useState<number | null>(null);
  const [editor, setEditor] = useState<number | null>(null);
  const closeEditor = useCallback(() => setEditor(null), []);
  const openEditor = useCallback((id: number) => { setDetails(null); setEditor(id); }, []);
  const editorChanged = useCallback((next: BookingEditorData) => { setData(previous => ({ ...previous, rows: previous.rows.map(row => row.id === next.booking.id ? next.booking : row), archived: previous.archived.map(row => row.id === next.booking.id ? next.booking : row) })); }, []);
  const [note, setNote] = useState(""), [phone, setPhone] = useState(""), [exporting, setExporting] = useState(false);
  const locks = useRef(new Set<string>()), table = useRef<HTMLTableElement>(null), mounted = useRef(true);
  useEffect(() => { mounted.current = true; Promise.resolve().then(() => { try { const p = JSON.parse(localStorage.getItem(PREFS) || "null"); if (Array.isArray(p?.hidden)) setHidden(p.hidden.filter((n: unknown) => Number.isInteger(n) && Number(n) >= 0 && Number(n) < 17)); if (Array.isArray(p?.widths) && p.widths.length === 17 && p.widths.every((n: unknown) => typeof n === "number" && n >= 55 && n <= 700)) setWidths(p.widths); } catch {} }); return () => { mounted.current = false; }; }, []);
  const visible = useMemo(() => archive ? data.archived.filter(row => bookingMatches(row, archiveQuery, archiveTrip, archiveStatus, archivePoster)) : data.rows.filter(row => bookingMatches(row, query, trip, status, poster)), [archive, data, archiveQuery, archiveTrip, archiveStatus, archivePoster, query, trip, status, poster]);
  const filtered = useMemo(() => data.rows.filter(row => bookingMatches(row, query, trip, status, poster)), [data.rows, query, trip, status, poster]);
  const summary = useMemo(() => bookingSummary(visible), [visible]);
  const currentYear = Number(data.today.slice(0, 4)), metrics = bookingAnalytics(filtered, currentYear, year, month);
  const years = [...new Set([String(currentYear), String(currentYear - 1), ...data.rows.map(row => row.date.slice(0, 4)).filter(value => Number(value) > 2000)])].sort().reverse();
  const activeDetails = [...data.rows, ...data.archived].find(row => row.id === details);
  const closeDetails = useCallback(() => setDetails(null), []);
  const chosen = selected.filter(id => visible.some(row => row.id === id && row.editable));
  const selectable = visible.filter(row => row.editable);
  function persistColumns(nextHidden: number[], nextWidths: number[]) { try { localStorage.setItem(PREFS, JSON.stringify({ hidden: nextHidden, widths: nextWidths })); } catch {} }
  function changeColumns(next: number[]) { setHidden(next); persistColumns(next, widths); }
  function resize(event: PointerEvent<HTMLButtonElement>, index: number) {
    event.preventDefault(); const element = event.currentTarget, x = event.clientX, width = widths[index]; element.setPointerCapture(event.pointerId);
    let next = [...widths];
    const move = (e: globalThis.PointerEvent) => { next = [...widths]; next[index] = Math.max(55, Math.min(700, width + e.clientX - x)); setWidths(next); };
    const end = () => { persistColumns(hidden, next); element.removeEventListener("pointermove", move); element.removeEventListener("pointerup", end); element.removeEventListener("pointercancel", end); };
    element.addEventListener("pointermove", move); element.addEventListener("pointerup", end); element.addEventListener("pointercancel", end);
  }
  const refresh = useCallback(async (page = data.page) => {
    if (locks.current.size || loading) return; setLoading(true); setNotice(null);
    try { const response = await fetch(`/api/admin/bookings?page=${page}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok || result.bookings_api_version !== "1.0.0") throw new Error(result.message || "Could not load bookings."); if (mounted.current) { setData(result); setSelected([]); } }
    catch (error) { if (mounted.current) setNotice({ text: error instanceof Error ? error.message : "Could not load bookings.", error: true }); }
    finally { if (mounted.current) setLoading(false); }
  }, [data.page, loading]);
  useEffect(() => {
    function checkChanged() {
      if (locks.current.size || loading) return;
      try { if (sessionStorage.getItem("tripanza-admin-bookings-changed") !== "1") return; sessionStorage.removeItem("tripanza-admin-bookings-changed"); } catch { return; }
      void refresh();
    }
    checkChanged(); window.addEventListener("focus", checkChanged); window.addEventListener("tripanza-booking-updated", checkChanged);
    return () => { window.removeEventListener("focus", checkChanged); window.removeEventListener("tripanza-booking-updated", checkChanged); };
  }, [refresh, loading]);
  async function mutate(action: string, payload: Record<string, unknown>, row?: AdminBooking) {
    const key = row ? String(row.id) : "bulk"; if (locks.current.has(key) || locks.current.has("bulk") || loading || (!row && locks.current.size)) return;
    locks.current.add(key); setBusy([...locks.current]); setNotice(null);
    try {
      const response = await fetch("/api/admin/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, nonce: data.nonce, ...(row ? { id: row.id, revision: row.revision } : {}), ...payload }) });
      const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.message || "The booking could not be saved.");
      if (!mounted.current) return;
      setData(prev => {
        const ids = new Set<number>(result.ids || []), updated: AdminBooking[] = result.rows || [];
        const all = [...prev.rows, ...prev.archived];
        const archiveDelta = action === "archive" ? all.filter(row => ids.has(row.id) && !row.archived).length : action === "restore" || action === "purge" ? -all.filter(row => ids.has(row.id) && row.archived).length : 0;
        return { ...prev, nonce: result.nonce || prev.nonce, archive_total: Math.max(0, prev.archive_total + archiveDelta), total: action === "purge" ? Math.max(0, prev.total - ids.size) : prev.total, rows: [...prev.rows.filter(row => !ids.has(row.id)), ...updated.filter(row => !row.archived)].sort((a, b) => b.id - a.id), archived: [...prev.archived.filter(row => !ids.has(row.id)), ...updated.filter(row => row.archived)].sort((a, b) => b.id - a.id) };
      });
      setSelected(result.failed_ids || []); setNotice({ text: result.warning ? `${result.message} ${result.warning}` : result.message, error: Boolean(result.warning || result.failed_ids?.length) });
    } catch (error) { if (mounted.current) setNotice({ text: error instanceof Error ? error.message : "The booking could not be saved.", error: true }); }
    finally { locks.current.delete(key); if (mounted.current) setBusy([...locks.current]); }
  }
  async function bulk(action: "archive" | "restore" | "purge") {
    if (!chosen.length) return;
    if (action === "purge") { if (window.prompt(`Permanently delete ${chosen.length} archived booking(s)? This cannot be undone. Type DELETE PERMANENTLY to confirm.`) !== "DELETE PERMANENTLY") return; }
    else if (!window.confirm(`${action === "archive" ? "Move to archive" : "Restore"} ${chosen.length} booking(s)?${action === "archive" ? " Booking records will be kept." : ""}`)) return;
    await mutate(action, { ids: chosen, ...(action === "purge" ? { confirmation: "DELETE PERMANENTLY" } : {}) });
  }
  async function exportPdf() {
    if (!visible.length) { setNotice({ text: "No bookings match the current filters.", error: true }); return; }
    setExporting(true);
    try { const { exportBookingReport } = await import("@/lib/admin-bookings-export"); await exportBookingReport(visible, hidden, note, [query && `Booking: ${query}`, trip && `Trip: ${trip}`, status && `Status: ${status}`, poster && `Posted by: ${poster}`].filter(Boolean).join(" | ") || "All active bookings"); }
    catch { setNotice({ text: "Could not generate the report. Please try again.", error: true }); }
    finally { setExporting(false); }
  }
  function whatsapp() {
    let digits = phone.replace(/\D/g, ""); if (digits.length === 10) digits = "91" + digits;
    if (!/^[1-9]\d{9,14}$/.test(digits) || !visible.length) { setNotice({ text: "Enter a valid coordinator WhatsApp number and select a view with bookings.", error: true }); return; }
    window.open(`https://wa.me/${digits}?text=${encodeURIComponent(coordinatorMessage(visible))}`, "_blank", "noopener,noreferrer");
  }
  function selection(id: number) { setSelected(prev => prev.includes(id) ? prev.filter(value => value !== id) : [...prev, id]); }
  function filter(set: (value: string) => void, value: string) { set(value); setSelected([]); }
  const filters = (archived: boolean) => <div className={`tz-board__bar tz-board__filters controls-grid${archived ? " tz-archive-filters" : ""}`}><form onSubmit={event => event.preventDefault()}><label htmlFor={archived ? "archiveSearchInput" : "searchInput"}>Booking ID / date</label><input id={archived ? "archiveSearchInput" : "searchInput"} placeholder="Search ID, customer, phone, or departure" value={archived ? archiveQuery : query} onChange={event => filter(archived ? setArchiveQuery : setQuery, event.target.value)} /></form><form onSubmit={event => event.preventDefault()}><label htmlFor={archived ? "archiveTitleSearchInput" : "titleSearchInput"}>Trip</label><input id={archived ? "archiveTitleSearchInput" : "titleSearchInput"} placeholder="Search trip name" value={archived ? archiveTrip : trip} onChange={event => filter(archived ? setArchiveTrip : setTrip, event.target.value)} /></form><form onSubmit={event => event.preventDefault()}><label htmlFor={archived ? "archiveStatusSearchInput" : "statusSearchInput"}>Status</label><select id={archived ? "archiveStatusSearchInput" : "statusSearchInput"} value={archived ? archiveStatus : status} onChange={event => filter(archived ? setArchiveStatus : setStatus, event.target.value)}><option value="">All statuses</option>{[...new Set(Object.values(data.statuses))].map(label => <option key={label}>{label}</option>)}</select></form>{archived && <div className="tz-filter-field"><label>Posted by</label><div className="tz-archive-poster-seg">{[["", "All"], ["admin", "Admin"], ["host", "Hosts"]].map(([value, label]) => <button key={value} className={`tz-archive-poster-btn${archivePoster === value ? " is-active" : ""}`} onClick={() => filter(setArchivePoster, value)}>{label}</button>)}</div></div>}</div>;
  const bulkbar = <div className={`tz-bulk-bar${archive ? " tz-bulk-bar--archive" : ""}`}><div className="tz-bulk-bar__left"><label className="tz-bulk-select-all"><input type="checkbox" aria-label="Select visible bookings" checked={selectable.length > 0 && chosen.length === selectable.length} onChange={event => setSelected(event.target.checked ? selectable.map(row => row.id) : [])} /><span>Select visible</span></label><span className="tz-bulk-count"><strong>{chosen.length}</strong> selected</span></div><div className="tz-bulk-bar__actions">{archive ? <><button id="tzBulkRestoreBtn" disabled={!chosen.length || busy.length > 0 || loading} onClick={() => bulk("restore")}><Icon name="fa-rotate-left" /> Restore selected</button><button id="tzBulkPurgeBtn" disabled={!chosen.length || busy.length > 0 || loading} onClick={() => bulk("purge")}><Icon name="fa-trash" /> Delete permanently</button></> : <button id="tzBulkDeleteBtn" disabled={!chosen.length || busy.length > 0 || loading} onClick={() => bulk("archive")}><Icon name="fa-box-archive" /> Move to archive</button>}</div></div>;
  return <div className="native-admin-bookings"><AdminMenu name={data.user.name} wordpressOrigin={wordpressOrigin} /><main className="tz-booking-app"><div className="tz-container booking-dashboard-wrapper"><header className="tz-topbar"><div className="tz-topbar__brand"><div className="tz-mark"><Icon name="fa-route" /></div><div><span className="tz-topbar__eyebrow">Tripanza operations</span><h1>Global Booking History</h1><p>One workspace for bookings, payments and traveller operations</p></div></div><span className="tz-live-pill"><i /> Live operations</span><div className="tz-seg">{[["", "All"], ["admin", "Admin"], ["host", "Hosts"]].map(([value, label]) => <button key={value} className={`tz-seg-btn${poster === value ? " is-active" : ""}`} onClick={() => filter(setPoster, value)}>{label}</button>)}</div><div className="tz-seg tz-view-seg"><button className={`tz-view-btn${!archive ? " is-active" : ""}`} onClick={() => { setArchive(false); setSelected([]); }}>Active</button><button className={`tz-view-btn${archive ? " is-active" : ""}`} onClick={() => { setArchive(true); setSelected([]); }}>Archive <span className="tz-view-badge">{data.archive_total}</span></button></div></header>
    {notice && <div className={`nb-notice${notice.error ? " is-error" : ""}`} role={notice.error ? "alert" : "status"}>{notice.text}<button aria-label="Dismiss notice" onClick={() => setNotice(null)}>×</button></div>}
    <div id="tzActiveWorkspace" hidden={archive}><div className="tz-overview"><div className="tz-kpis">{[["Confirmed bookings", String(metrics.count), "Bookings ready to travel", "fa-circle-check", "tzValConfirmed"], ["Confirmed revenue", money(metrics.total), "Collected and partially paid", "fa-indian-rupee-sign", "tzValRevenue"], ["Total persons", String(metrics.persons), "Travellers across this view", "fa-user-group", "tzValPersons"]].map(([label, value, help, icon, id]) => <div className="tz-kpi" key={id}><div className="tz-kpi__icon"><Icon name={icon} /></div><div><span>{label}</span><strong id={id}>{value}</strong><small>{help}</small></div></div>)}</div><div className="tz-chart-card"><div className="tz-chart-card__head"><div className="tz-chart-card__title"><h3>Revenue · last 2 years</h3><small>Fully paid + partially paid</small></div><div className="tz-filters-inline tz-chart-filters"><select id="tzYearFilter" aria-label="Analytics year" value={year} onChange={event => setYear(event.target.value)}><option value="all">All Years</option>{years.map(y => <option key={y}>{y}</option>)}</select><select id="tzMonthFilter" aria-label="Analytics month" value={month} onChange={event => setMonth(event.target.value)}><option value="all">All Months</option>{MONTHS.map((m, index) => <option value={index} key={m}>{m}</option>)}</select><select aria-label="Analytics booking source" value={poster} onChange={event => filter(setPoster, event.target.value)}><option value="">All Bookings</option><option value="admin">Admin Bookings</option><option value="host">Host / Partner Bookings</option></select></div></div><AdminBookingCharts rows={filtered} year={currentYear} /></div></div>
    <section className="tz-board"><div className="tz-board__intro"><div><span>Booking workspace</span><h2>Find, review and manage every trip.</h2></div><p>Filters update the booking list and summary instantly.</p></div>{filters(false)}<div className="tz-board__bar tz-board__actions"><label htmlFor="customText">PDF note</label><label htmlFor="coordinatorPhone">Coordinator WhatsApp</label><textarea id="customText" rows={1} maxLength={2000} placeholder="Optional export note" value={note} onChange={event => setNote(event.target.value)} /><input id="coordinatorPhone" type="tel" placeholder="e.g. 919876543210" value={phone} onChange={event => setPhone(event.target.value)} /><div className="tz-board__tools master-actions"><button id="exportButton" disabled={exporting} onClick={exportPdf}><Icon name="fa-file-pdf" /> {exporting ? "Exporting…" : "Export"}</button><button id="whatsappShareButton" onClick={whatsapp}><i className="fa-brands fa-whatsapp" aria-hidden="true" /> WhatsApp</button></div></div><div className="tz-column-pills"><span className="tz-column-pills__label">Columns</span><div className="toggle-buttons"><button id="showAll" className="tz-pill-action" onClick={() => changeColumns([])}>Show all</button><button id="hideAll" className="tz-pill-action tz-pill-action--muted" onClick={() => changeColumns(BOOKING_COLUMNS.map((_, index) => index))}>Hide all</button>{BOOKING_COLUMNS.map((label, index) => <button key={label} data-col={index} aria-pressed={!hidden.includes(index)} className={!hidden.includes(index) ? "active" : ""} onClick={() => changeColumns(hidden.includes(index) ? hidden.filter(col => col !== index) : [...hidden, index])}>{label}</button>)}</div></div>{!archive && bulkbar}<div className="table-responsive-wrapper"><table ref={table} id="tzBookingHistoryTable" className="table table-bordered table-striped table-booking-history" style={{ width: widths.reduce((sum, width, index) => sum + (hidden.includes(index) ? 0 : width), 0) }}><colgroup>{widths.map((width, index) => <col key={index} hidden={hidden.includes(index)} style={{ width }} />)}</colgroup><thead><tr>{BOOKING_COLUMNS.map((label, index) => <th key={label} hidden={hidden.includes(index)}>{label}<button className="tz-col-resizer" aria-label={`Resize ${label} column`} onPointerDown={event => resize(event, index)} onKeyDown={event => { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { const next = [...widths]; next[index] = Math.max(55, Math.min(700, widths[index] + (event.key === "ArrowLeft" ? -10 : 10))); setWidths(next); persistColumns(hidden, next); } }} /></th>)}</tr></thead><tbody>{filtered.map((row, index) => {
      const pending = busy.includes(String(row.id)) || busy.includes("bulk") || loading;
      const cells: ReactNode[] = [<label key="select" className="tz-row-check"><input type="checkbox" aria-label={`Select booking #${row.id}`} checked={selected.includes(row.id)} disabled={!row.editable || pending} onChange={() => selection(row.id)} />{(data.page - 1) * data.per_page + index + 1}</label>, row.id, <span key="departure">{row.departure}<br />Duration: {row.duration || "—"}</span>, <Trip key="trip" row={row} />, <div key="customer">{row.customer}{row.guests.length > 0 && <div className="item_booking_detail"><strong>Guest Name:</strong><br />{row.guests.join(", ")}</div>}</div>, row.phone, <span key="sharing">{row.quad > 0 && <>Quad {row.quad}<br /></>}{row.triple > 0 && <>Triple {row.triple}<br /></>}{row.twin > 0 && <>Twin {row.twin}<br /></>}<strong>Total: {row.persons}</strong></span>, row.addons.length ? <div key="addons">{row.addons.map((item, index) => <p key={index}><strong>{item.label}</strong> {item.qty} {item.unit}{item.price > 0 && <><br />{money(item.price * item.qty, row.currency)}</>}{item.detail && <><br />{item.detail}</>}</p>)}</div> : "No Add-ons", number(row.total), number(row.advance), row.balance === 0 ? "Zero Balance" : number(row.balance), <Adjustment key={`adjustment-${row.revision}`} row={row} disabled={pending || !row.editable} save={amount => mutate("adjustment", { amount }, row)} />, <div key="payment"><select className="admin-order-status nb-status-select" aria-label={`Booking #${row.id} status`} value={row.status_key} disabled={pending || !row.editable} onChange={event => mutate("status", { status: event.target.value }, row)}>{Object.entries(data.statuses).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="btn-xs resend-email-btn" disabled={pending || !data.mail_available || !row.editable} onClick={() => mutate("resend", {}, row)}>{pending ? "Saving…" : "Resend Email"}</button>{!row.editable && <small>Legacy booking: use the full editor.</small>}</div>, row.status, <button key="details" className="btn-xs open-side-modal" onClick={() => setDetails(row.id)}><Icon name="fa-circle-info" /> Details</button>, <button key="edit" type="button" className="btn-xs" disabled={pending} onClick={() => openEditor(row.id)} title="Edit booking without leaving history"><Icon name="fa-pencil" /> Edit</button>, <a key="invoice" className="btn-xs" href={row.invoice_url} target="_blank" rel="noopener noreferrer"><Icon name="fa-file-pdf" /> Download invoice</a>];
      return <tr className={`order-row${selected.includes(row.id) ? " is-selected" : ""}`} key={row.id} data-order-id={row.id} data-poster-type={row.poster} data-order-status={row.status}>{cells.map((cell, col) => <td key={col} hidden={hidden.includes(col)} data-label={BOOKING_COLUMNS[col]} className={col === 13 ? "status-display" : col >= 8 && col <= 10 ? "tz-col-money-cell" : col === 6 ? "tz-col-person-cell" : col === 11 ? "tz-col-adjustment-cell" : col === 12 ? "tz-col-payment-cell" : col === 0 ? "tz-col-sno-cell" : undefined}>{cell}</td>)}</tr>;
    })}{!filtered.length && <tr><td colSpan={17} className="nb-empty">No bookings match the current filters.</td></tr>}</tbody></table></div><Summary rows={filtered} /></section></div>
    <div id="tzArchiveWorkspace" className="tz-archive-workspace" hidden={!archive}><section className="tz-board tz-board--archive"><div className="tz-archive-head"><div><h2>Archived bookings</h2><p>Moved out of the active list. Restore to bring them back.</p></div><span className="tz-archive-pill">{data.archive_total} archived</span></div>{filters(true)}<div className="tz-archive-filter-meta"><span><strong>{visible.length}</strong> visible</span><span>Use filters to narrow archived bookings</span></div>{archive && bulkbar}<div className="table-responsive-wrapper"><table className="table table-bordered table-striped table-booking-history tz-archive-table"><thead><tr>{["S.no.", "#ID", "Departure", "Trip", "Customer", "Phone", "Status", "Archived on"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{archive && visible.map((row, index) => <tr key={row.id} className="order-row tz-archive-row" data-order-id={row.id} data-poster-type={row.poster}>{[<label key="select" className="tz-row-check"><input type="checkbox" aria-label={`Select archived booking #${row.id}`} disabled={!row.editable || busy.length > 0} checked={selected.includes(row.id)} onChange={() => selection(row.id)} />{index + 1}</label>, row.id, row.departure, <Trip key="trip" row={row} />, row.customer, row.phone, row.status, row.archived_at || "—"].map((cell, col) => <td key={col} data-label={["S.no.", "#ID", "Departure", "Trip", "Customer", "Phone", "Status", "Archived on"][col]}>{cell}</td>)}</tr>)}{archive && !visible.length && <tr><td colSpan={8} className="nb-empty">No archived bookings match the current filters.</td></tr>}</tbody></table></div></section></div>
    <div className="nb-pagination"><button className="nb-refresh" disabled={loading || busy.length > 0} onClick={() => refresh()}>{loading ? "Loading…" : "Refresh bookings"}</button><span>Page {data.page} · Up to {data.per_page} records per page. Filters, totals and exports use this loaded page.</span>{data.page > 1 && <button disabled={loading || busy.length > 0} onClick={() => refresh(data.page - 1)}>← Previous</button>}{data.page * data.per_page < Math.max(data.total, data.archive_total) && <button disabled={loading || busy.length > 0} onClick={() => refresh(data.page + 1)}>Next →</button>}</div>{summary.count > 0 && new Set(visible.map(row => row.currency)).size > 1 && <p className="nb-muted">This view has mixed currencies. Aggregate financial figures are raw stored amounts, not currency-converted totals.</p>}
    </div></main>{activeDetails && <AdminBookingDetails row={activeDetails} close={closeDetails} edit={openEditor} />}{editor !== null && <AdminBookingEditorModal key={editor} id={editor} wordpressOrigin={wordpressOrigin} close={closeEditor} changed={editorChanged} />}</div>;
}
function Adjustment({ row, disabled, save }: { row: AdminBooking; disabled: boolean; save: (amount: string) => Promise<void> }) {
  const [value, setValue] = useState(String(row.adjustment));
  return <form className="adjustment-form" onSubmit={event => { event.preventDefault(); void save(value); }}><input name="admin_backend_adjustment" aria-label={`Booking #${row.id} adjustment`} type="number" step="0.01" value={value} onChange={event => setValue(event.target.value)} disabled={disabled} required /><button className="btn-modern" disabled={disabled} type="submit">Update</button></form>;
}
function Summary({ rows }: { rows: AdminBooking[] }) {
  const s = bookingSummary(rows), stat = (label: string, value: number) => <div className="tz-foot-stat" key={label}><strong>{label}</strong><span className="tz-foot-stat__val">{value}</span></div>;
  return <div className="nb-summary"><div className="tz-foot-card"><span className="tz-foot-card__title">Filtered summary</span><strong>{s.count} bookings</strong><p className="nb-muted">Based on current filters</p></div><div className="tz-foot-card"><span className="tz-foot-card__title">Guests</span>{stat("Total Male", s.male)}{stat("Total Female", s.female)}</div><div className="tz-foot-card"><span className="tz-foot-card__title">Persons</span>{stat("Quad", s.quad)}{stat("Triple", s.triple)}{stat("Twin", s.twin)}</div><div className="tz-foot-card"><span className="tz-foot-card__title">Rooms Required</span>{stat("Total Rooms", s.quadRooms + s.tripleRooms + s.twinRooms)}{stat("Quad Rooms", s.quadRooms)}{stat("Triple Rooms", s.tripleRooms)}{stat("Twin Rooms", s.twinRooms)}</div>{s.addons.length > 0 && <div className="tz-foot-card"><span className="tz-foot-card__title">Add-ons Total</span>{s.addons.map(item => stat(item.label, item.qty))}</div>}{(["total", "advance", "balance"] as const).map(key => <div className="tz-foot-card tz-foot-card--money" key={key}><span className="tz-foot-card__title">{key}</span><span className="tz-foot-card__value">{money(s[key], rows[0]?.currency || "INR")}</span></div>)}</div>;
}
