"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { HostDashboard, HostProfile } from "@/lib/host";
import "./dashboard-original.css";

const confirmed = ["complete", "fully_paid"];
const cancelled = ["cancelled", "canceled", "refunded"];
const number = (value: number) => Math.max(0, value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 });
const shortMoney = (value: number) => {
  const amount = Math.max(0, value || 0);
  if (amount >= 10_000_000) return `${(amount / 10_000_000).toFixed(1)}Cr`;
  if (amount >= 100_000) return `${(amount / 100_000).toFixed(1)}L`;
  if (amount >= 1_000) return `${(amount / 1_000).toFixed(1)}K`;
  return number(amount);
};
const statusLabel = (status: string) => ({ fully_paid: "Fully paid", complete: "Complete", partially_paid: "Part paid", on_hold: "On hold", cancelled: "Cancelled", canceled: "Cancelled", refunded: "Refunded", pending: "Pending" })[status as "fully_paid"] || status.replaceAll("_", " ");

export default function HostDashboardOriginal({ profile, data, setup }: { profile: HostProfile; data: HostDashboard; setup?: string }) {
  const [metric, setMetric] = useState<"revenue" | "earnings">("revenue");
  const league = useMemo(() => [...(data.leaderboard || [])].sort((left, right) => (right[metric] - left[metric]) || (right[metric === "revenue" ? "earnings" : "revenue"] - left[metric === "revenue" ? "earnings" : "revenue"])), [data.leaderboard, metric]);
  const rank = league.findIndex(host => host.id === profile.id) + 1;
  const maxRevenue = Math.max(1, ...(data.months || []).map(month => month.revenue));
  const cards = [
    ["Total host revenue", data.stats.revenue, "Confirmed booking value generated by your trips."],
    ["Your profit earned", data.stats.earnings, "Final host commission after adjustments."],
    ["Wallet now", data.wallet_balance || 0, "Available for the next payout."],
    ["Paid to bank", data.bank_paid || 0, "Completed host payouts recorded."],
  ] as const;
  const actions = [["✈", "Build trips", "Pick or create a departure", "/admin-host-trips"], ["▶", "Drop a reel", "Turn moments into bookings", "/host-reels"], ["₹", "Open wallet", "Track every money move", "/host-wallet"], ["☻", "Meet the crew", "View traveller bookings", "/host-customer-booking-history"]] as const;

  return <div className="hd-page"><main className="hd-shell">
    <header className="hd-top"><Link className="hd-brand" href="/"><i className="hd-mark">T</i><span><small>TRIPANZA HOST MODE</small><strong>{profile.name}</strong></span></Link><Link className="hd-profile" href={`/host/${profile.slug}`}><span>View public profile{profile.verified ? " ✓" : ""}</span><i className="hd-avatar">{profile.logo ? <img src={profile.logo} alt="" /> : profile.name.slice(0, 1).toUpperCase()}</i></Link></header>
    {setup === "logo" && <div className="hd-ready" role="status">Your host account was created, but the logo did not upload. Add it from your public profile.</div>}
    <section className="hd-hero"><div><span className="hd-kicker">YOUR HOST COMMAND CENTRE</span><h1>Hey {data.first_name || profile.name}.<br /><em>The crew is moving.</em></h1><p>One honest view of what travellers booked, what you earned and what is ready to move into your bank.</p></div><div className="hd-live"><i /><span><small>LIVE TRIPS</small><strong>{number(data.stats.trips)} ready for crews</strong></span></div></section>
    <section className="hd-money">{cards.map(([label, amount, caption]) => <article key={label}><small>{label}</small><strong><b>₹</b>{number(amount)}</strong><span>{caption}</span></article>)}</section>
    <section className="hd-layout"><article className="hd-panel"><header className="hd-panel-head"><div><span>LAST SIX MONTHS</span><h2>Revenue pulse</h2></div><Link href="/host-customer-booking-history">Full booking desk →</Link></header><div className="hd-chart">{(data.months || []).map((month, index) => <div className="hd-bar" key={`${month.label}-${index}`}><span>₹{shortMoney(month.revenue)}</span><div className="hd-track"><i className="hd-fill" style={{ height: `${month.revenue > 0 ? Math.max(4, month.revenue / maxRevenue * 100) : 2}%` }}><i style={{ height: `${month.revenue > 0 ? Math.min(92, Math.max(3, month.profit / month.revenue * 100)) : 0}%` }} /></i></div><small>{month.label}</small></div>)}</div></article>
      <aside className="hd-panel"><header className="hd-panel-head"><div><span>RIGHT NOW</span><h2>Trip snapshot</h2></div></header><div className="hd-snapshot">{[["✓", "Confirmed bookings", "Completed and fully paid", number(data.stats.confirmed)], ["☻", "Travellers booked", "Across confirmed crews", number(data.stats.guests)], ["→", "Upcoming departures", "Active bookings ahead", number(data.upcoming || 0)], ["₹", "Profit in pipeline", "Not finalized yet", `₹${shortMoney(data.stats.pipeline)}`]].map(([icon, label, caption, value]) => <div className="hd-row" key={label}><i>{icon}</i><span><b>{label}</b><small>{caption}</small></span><strong>{value}</strong></div>)}</div><div className="hd-ready"><b>{data.payout_ready ? "Payout destination ready." : "Your payout setup needs one minute."}</b><span>{data.payout_ready ? "Eligible wallet earnings can be transferred using your secured details." : "Add your bank account or UPI before the next payout run."}</span><Link href="/host-payout-details">{data.payout_ready ? "View payout details" : "Finish payout setup"} →</Link></div></aside>
    </section>
    <section className="hd-panel hd-league"><header className="hd-league-head"><div><span>THIS MONTH&apos;S HOST LEAGUE</span><h2>Fill crews. Climb ranks.</h2><p>Only confirmed bookings count. Revenue brings reach; earnings bring the crown.</p></div><div className="hd-league-controls"><strong>{rank ? `YOUR RANK #${rank}` : "YOUR RANK STARTS NOW"}</strong><div className="hd-tabs" role="group" aria-label="Rank leaderboard by"><button className={metric === "revenue" ? "active" : ""} type="button" onClick={() => setMetric("revenue")}>Revenue</button><button className={metric === "earnings" ? "active" : ""} type="button" onClick={() => setMetric("earnings")}>Earnings</button></div></div></header>
      {league.length ? <div className={`hd-league-list${metric === "earnings" ? " show-earnings" : ""}`}>{league.map((host, index) => <Link href={`/host/${host.slug}`} className={`hd-league-row${host.id === profile.id ? " you" : ""}`} key={host.id}><span className={`hd-rank${index === 0 ? " top" : index === 1 ? " second" : index === 2 ? " third" : ""}`}>{index + 1}</span><i className="hd-league-avatar">{host.avatar ? <img src={host.avatar} alt="" /> : host.name.slice(0, 1).toUpperCase()}</i><span className="hd-league-name"><b>{host.name}{host.verified ? " ✓" : ""}</b><small>{number(host.bookings)} confirmed bookings{host.id === profile.id && <em>YOU</em>}</small></span><span className="hd-league-value revenue"><small>REVENUE</small><strong>₹{shortMoney(host.revenue)}</strong></span><span className="hd-league-value earnings"><small>EARNINGS</small><strong>₹{shortMoney(host.earnings)}</strong></span></Link>)}</div> : <div className="hd-league-empty">The monthly race starts with the first confirmed booking.</div>}
    </section>
    <nav className="hd-actions">{actions.map(([icon, title, caption, href]) => <Link className="hd-action" href={href} key={href}><i>{icon}</i><span><b>{title}</b><small>{caption}</small></span></Link>)}</nav>
    <section className="hd-panel hd-bookings"><header className="hd-panel-head"><div><span>LATEST MOVEMENT</span><h2>Recent bookings</h2></div><Link href="/host-customer-booking-history">See all →</Link></header>{data.recent_bookings.length ? <div className="hd-list">{data.recent_bookings.map(order => <article className="hd-booking" key={order.id}><span className="hd-id">#{order.id}</span><div className="hd-main"><b>{order.tour_title}</b><small>{order.customer} · {number(order.guests)} travellers · {new Date(order.created_at).toLocaleDateString("en-IN", { day: "2-digit", month: "short" })}</small></div><div className="hd-booking-money revenue"><small>BOOKING VALUE</small><strong>₹{shortMoney(order.total)}</strong></div><div className="hd-booking-money profit"><small>YOUR PROFIT</small><strong>₹{shortMoney(order.host_earnings)}</strong></div><span className={`hd-status${confirmed.includes(order.status) ? " good" : cancelled.includes(order.status) ? " bad" : ""}`}>{order.bank_paid ? "Paid out" : order.commission_credited ? "In wallet" : statusLabel(order.status)}</span></article>)}</div> : <div className="hd-empty"><i>✈</i><h3>Your first booking lands here.</h3><p>Publish a trip, rally your people and start forming the crew.</p><Link href="/admin-host-trips">Explore host trips</Link></div>}</section>
  </main></div>;
}
