"use client";

import Link from "next/link";
import { useState } from "react";
import type { HostProfile } from "@/lib/host";

const money = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;

export default function HostProfileCommerce({ profile }: { profile: HostProfile }) {
  const [slides, setSlides] = useState<Record<number, number>>({});
  const deals = profile.deals || [];
  const stays = profile.stays || [];

  return <>
    {!!deals.length && <section className="tp-host-deals" id="tpHostDealDrops"><div className="tp-host-deals__shell"><header className="tp-host-deals__head"><span>Deal drop</span><h2>Your budget just <em>caught a break.</em></h2></header><div className="tp-host-deals__rail">{deals.map((deal, index) => <Link className="tp-host-deal" href={`/tours/${deal.slug}`} key={`${deal.slug}-${index}`}><span className="tp-host-deal__media"><img src={deal.cover} alt={deal.title} /><i aria-hidden="true">{deal.tags.some(tag => tag.kind === "cashback") ? "₹" : "%"}</i></span><span className="tp-host-deal__body"><span className="tp-host-deal__tags">{deal.tags.map(tag => <span className={`tp-host-deal__tag tp-host-deal__tag--${tag.kind}`} key={`${tag.kind}-${tag.label}`}>{tag.label}</span>)}</span><strong>{deal.title}</strong><span className="tp-host-deal__meta"><span>{deal.destination}</span><span>{deal.duration} days</span></span><span className="tp-host-deal__bottom"><span className="tp-host-deal__price"><small>Trip from</small><b>{deal.price > 0 ? money(deal.price) : "Check dates"}{deal.old_price > deal.price && <del>{money(deal.old_price)}</del>}</b></span><span className="tp-host-deal__cta">See deal →</span></span></span></Link>)}</div><p className="tp-host-deals__truth">Only configured discounts, cashback and live offers are shown here.</p></div></section>}
    {!!stays.length && <section className="tp-host-stays"><div className="tp-host-stays__shell"><header className="tp-host-stays__head"><div><span>Sleep scene</span><h2>Where you&apos;ll wake up matters.</h2></div><div className="tp-host-stays__trust"><i>✓</i><span><strong>No room roulette</strong><small>Real stays. Actually checked.</small></span></div></header><div className="tp-host-stays__guide"><span>✦</span>Swipe through the rooms. Screenshot your favourite.</div><div className="tp-host-stay-rail" aria-label={`Stays included in ${profile.name} trips`}>{stays.map((stay, index) => { const active = slides[index] || 0; return <article className={`tp-host-stay ${stay.images.length > 1 ? "has-gallery" : ""}`} key={`${stay.tour_slug}-${index}`}><div className="tp-host-stay__slides">{stay.images.map((image, imageIndex) => <Link className={`tp-host-stay__slide ${imageIndex === active ? "is-active" : ""}`} href={`/tours/${stay.tour_slug}`} key={image} aria-hidden={imageIndex !== active} tabIndex={imageIndex === active ? 0 : -1}><img src={image} alt={`${stay.title} accommodation photo ${imageIndex + 1}`} /></Link>)}</div>{stay.images.length > 1 && <><div className="tp-host-stay__nav"><button type="button" aria-label="Previous accommodation photo" onClick={() => setSlides(current => ({ ...current, [index]: (active - 1 + stay.images.length) % stay.images.length }))}>←</button><button type="button" aria-label="Next accommodation photo" onClick={() => setSlides(current => ({ ...current, [index]: (active + 1) % stay.images.length }))}>→</button></div><div className="tp-host-stay__dots" aria-label="Accommodation gallery">{stay.images.map((_, imageIndex) => <button type="button" className={active === imageIndex ? "is-active" : ""} key={imageIndex} aria-label={`Show photo ${imageIndex + 1}`} aria-pressed={active === imageIndex} onClick={() => setSlides(current => ({ ...current, [index]: imageIndex }))} />)}</div></>}<Link className="tp-host-stay__copy" href={`/tours/${stay.tour_slug}`}><small>{stay.tour_title}</small><strong>{stay.title}</strong><span>{stay.location && <i>{stay.location}</i>}<i>{stay.type}</i>{stay.amenities.map(amenity => <i key={amenity}>{amenity}</i>)}</span></Link></article>; })}</div><p className="tp-host-stays__note">Property is subject to availability; a similar or upgraded stay may be arranged when required.</p></div></section>}
  </>;
}
