import Link from "next/link";
import FeatureGate from "@/components/settings/FeatureGate";

const playlists = [
  ["Rasta — The Best Hindi Travel Playlist", "Primary · Hindi road-trip energy", "https://open.spotify.com/playlist/0SsEPM8tO7hXzNpMw5ptDV"],
  ["2026 Travel Jukebox", "Secondary · Hindi drive songs", "https://open.spotify.com/playlist/4p20iuxiOfWN4ViRQFkSvH"],
  ["Hindi road-trip songs", "Bollywood and safar favourites", "https://open.spotify.com/playlist/1qk7sHSUKBuKeDaMeTQqMY"],
  ["Hindi travel vibes", "Feel-good songs for the crew", "https://open.spotify.com/playlist/3S3O5JTK6prLIw43qrWtrJ"],
  ["Classic road-trip songs", "English classics for long drives", "https://open.spotify.com/playlist/37i9dQZF1DX9wC1KY45plY"],
];
const playlistCovers = [
  "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da8422a0218bfe2136bcfb502037",
  "https://image-cdn-fa.spotifycdn.com/image/ab67706c0000da84bbe00e51c92613f758d23ab4",
  "https://image-cdn-fa.spotifycdn.com/image/ab67706c0000da84d7315322b14694ff0e20e5f8",
  "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84cd21295f3226bc0d04f83db7",
  "https://i.scdn.co/image/ab67706f0000000250c7781777a3b0662fce5426",
];

const faqs = [
  ["Can I join a Tripanza trip alone?", "Yes. These community trips welcome solo travellers as well as friends, and the trip team helps everyone settle into the group."],
  ["Who usually joins?", "This youth collection is designed for travellers aged 18–28. Check the individual trip page for its batch and audience details."],
  ["How does Tripanza support women travellers?", "Stay, transport, captain and batch details are shared where available, with human support before and during the trip. Ask us anything before booking."],
  ["Who leads the group?", "Group departures are supported by the trip captain or team shown on the trip page. The exact setup can vary by experience."],
  ["How much do I pay now?", "It depends on the trip. Checkout shows the price breakdown, valid discounts, taxes, advance payable now and remaining balance before payment."],
];

export default function HostProfileEditorial({ slug, helpUrl }: { slug: string; helpUrl?: string }) {
  return <>
    <section className="tp-host-community"><div className="tp-host-community__card"><div className="tp-host-community__copy"><span>Your kind of crowd</span><h2>People you&apos;ll actually click with.</h2><p>Join solo or with a friend. These trips are designed for an 18-28 community, with clear group plans, verified teams and captains who help strangers feel included.</p><div className="tp-host-community__pills"><span>Solo-friendly</span><span>18-28 community</span><span>Women-friendly</span><span>Captain-supported</span></div></div><div className="tp-host-community__collage" aria-hidden="true"><img src="https://tripanza.com/wp-content/uploads/2022/09/WhatsApp-Image-2022-09-16-at-2.04.56-AM.jpeg" alt="" /><img src="https://tripanza.com/wp-content/uploads/2021/06/WhatsApp-Image-2021-07-12-at-2.28.22-AM-15-e1662666832961.jpeg" alt="" /><strong>Strangers on day one.<br />Inside jokes by day two.</strong></div></div></section>
    <section className="tp-host-international"><div className="tp-host-international__shell"><header className="tp-host-international__head"><div><span>Next stamp incoming</span><h2>Passport ready. Group chat pending.</h2></div><div className="tp-host-international__stamps" aria-hidden="true"><span>Visa era loading</span><span>Boarding soon ✈</span></div></header><div className="tp-host-international__card"><div className="tp-host-international__copy"><small>Your passport era starts here</small><h3>International trips are almost boarding.</h3><p>Bali, Vietnam, Thailand and more are on our radar. Join the drop list—no spam, just launch updates and real departures.</p><div className="tp-host-international__destinations"><span>Bali</span><span>Vietnam</span><span>Thailand</span><span>More loading…</span></div><a href={helpUrl || "/contact"} target={helpUrl ? "_blank" : undefined} rel={helpUrl ? "noopener noreferrer" : undefined}>Get on the first-drop list</a></div><div className="tp-host-international__visual" aria-hidden="true"><div className="tp-host-international__souvenirs"><span>📷</span><span>🧳</span><span>🌴</span></div><span className="tp-host-passport"><small>TRIPANZA</small><i>✦</i><strong>PASSPORT</strong><em>WORLD TRIP ERA</em></span><span className="tp-host-boarding-pass"><small>DEL</small><b>✈</b><small>WORLD</small></span><i className="tp-host-travel-stamp is-bali">Bali<br />next?</i><i className="tp-host-travel-stamp is-vietnam">Vietnam<br />next?</i></div></div></div></section>
    <section className="tp-host-paylater"><div className="tp-host-paylater__shell"><div className="tp-host-paylater__card"><div className="tp-host-paylater__grid"><div className="tp-host-paylater__copy"><span className="tp-host-paylater__kicker">Plot twist for your trip budget</span><h2><del>Pay now. Travel later.</del><span>Travel now. Pay later.</span></h2><p>On eligible bookings, choose an available EMI or Pay Later option at checkout and split the trip cost into manageable payments.</p><div className="tp-host-paylater__actions"><Link href="/?tripanza_view=all#trips">Find your next trip</Link><small>Available options are shown securely at checkout.</small></div></div><div className="tp-host-paylater__visual" aria-hidden="true"><div className="tp-host-paylater__pass"><div className="tp-host-paylater__route"><span><small>FROM</small><strong>Someday</strong></span><b>✈</b><span><small>TO</small><strong>Right now</strong></span></div><div className="tp-host-paylater__months"><span><small>Step 1</small><strong>Pick trip</strong></span><span><small>Step 2</small><strong>Choose EMI</strong></span><span><small>Step 3</small><strong>Pack bags</strong></span></div><div className="tp-host-paylater__powered"><span>PayU-supported checkout</span><b>PayU</b></div></div><span className="tp-host-paylater__sticker">Trip first<br />EMIs after</span></div></div><div className="tp-host-paylater__banks"><small>EMI options across major eligible banks</small><span>HDFC</span><span>ICICI</span><span>SBI</span><span>AXIS</span><span>Kotak</span><span>Bank of Baroda</span></div><p className="tp-host-paylater__fine">EMI, Pay Later, interest, tenure and eligibility depend on the issuing bank, payment method, transaction value and the options returned securely at checkout.</p></div></div></section>
    <section className="tp-host-playlist"><div className="tp-host-playlist__shell"><header className="tp-host-playlist__head"><div><span>Tripanza on AUX</span><h2>Put this on before the aux war starts.</h2></div><span className="tp-host-playlist__spotify"><i>♫</i>Opens in Spotify</span></header><div className="tp-host-playlist__rail">{playlists.map(([title, description, url], index) => <article className="tp-host-track" key={url}><a className="tp-host-track__cover" href={url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${title} on Spotify`}><img src={playlistCovers[index]} alt="" /><span>Spotify travel playlist</span></a><div className="tp-host-track__body"><small>Playlist {String(index + 1).padStart(2, "0")}</small><h3>{title}</h3><p>{description}</p><span className="tp-host-track__progress" /><span className="tp-host-track__time"><span>0:42</span><span>3:21</span></span><nav className="tp-host-track__controls"><a href={url} target="_blank" rel="noopener noreferrer">◀</a><a href={url} target="_blank" rel="noopener noreferrer">▶</a><a href={url} target="_blank" rel="noopener noreferrer">▶❘</a></nav></div></article>)}</div></div></section>
    <section className="tp-host-faq"><div className="tp-host-faq__layout"><div className="tp-host-faq__intro"><span className="tp-host-faq__kicker">No awkward questions</span><h2>Ask before the group chat does.</h2><p>Straight answers for first-time community travellers. No confusing travel jargon.</p><div className="tp-host-faq__pills" aria-hidden="true"><span>Solo aa sakte hain?</span><span>Girls ke liye safe?</span><span>Kitna pay now?</span></div><a className="tp-host-faq__human" href={helpUrl || "/contact"} target={helpUrl ? "_blank" : undefined} rel={helpUrl ? "noopener noreferrer" : undefined}>Still confused? Ask a human</a></div><div className="tp-host-faq__list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0 ? true : undefined}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
    <section className="tp-host-help"><div className="tp-host-help__card"><div className="tp-host-help__copy"><span className="tp-host-help__icon" aria-hidden="true">💬</span><div><small>Real human. Real reply.</small><h3>Group chat stuck?</h3><p>Dates, budget ya pickup—bas ping karo. We will help you pick.</p></div></div><div className="tp-host-help__chips" aria-hidden="true"><span>Dates?</span><span>Budget?</span><span>Pickup?</span></div><a href={helpUrl || "/contact"} target={helpUrl ? "_blank" : undefined} rel={helpUrl ? "noopener noreferrer" : undefined}>{helpUrl ? "Ask on WhatsApp" : "Contact us"}</a></div></section>
    <section className="tp-host-final"><div className="tp-host-final__card"><h2>Stop reacting to reels. <span>Go make one.</span></h2><div className="tp-host-final__actions"><a href="#tpHostTrips">Find my next trip</a><FeatureGate feature="reels_enabled"><Link href={`/host/${slug}/reels`}>Watch trip drops</Link></FeatureGate></div></div><footer className="tp-host-final__footer">India&apos;s coolest travel app <span aria-hidden="true">♥</span></footer></section>
  </>;
}
