"use client";
import { useEffect, useRef, useState } from "react";
import { apiFetch } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";
import { zonedIso } from "@/lib/automationTime";
import { Clock, Radio, Send, Zap, Users, Link2, MousePointer2, RefreshCw, Plus, Trash2, Download } from "lucide-react";
type Item = Record<string, any>;
type Button = {
    kind: "url" | "reply";
    label: string;
    value: string;
};
type Payload = {
    text: string;
    media?: {
        kind: string;
        url: string;
        fileName: string;
    };
    buttons?: Button[];
    template?: {
        name: string;
        language: string;
        parameters: string[];
    };
};
const input = "w-full min-w-0 rounded-xl border border-slate-300 bg-slate-50 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-brand-600";
const card = "min-w-0 max-w-full rounded-2xl border border-slate-200 bg-white/70 p-5 space-y-4";
const btn = "inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-4 py-2.5 text-sm text-slate-800 hover:bg-slate-100 disabled:opacity-40";
const primary = "inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-700 disabled:opacity-40";
const split = (value: string) => value.split(/[\s,;]+/).map(item => item.trim()).filter(Boolean);
const emptyPayload = (): Payload => ({ text: "", buttons: [] });
function Field({ title, children }: {
    title: string;
    children: React.ReactNode;
}) {
    return <label className="block min-w-0 space-y-2 text-xs font-medium text-slate-600"><span>{title}</span>{children}</label>;
}
function Composer({ value, onChange, cloud }: {
    value: Payload;
    onChange: (value: Payload) => void;
    cloud?: boolean;
}) {
    const buttons = value.buttons || [];
    return <div className="space-y-4">
    <Field title="Message · WhatsApp *headings*, bullets and _highlights_ supported"><textarea required={!value.media && !value.template} maxLength={4000} rows={5} className={input} value={value.text} onChange={e => onChange({ ...value, text: e.target.value })} placeholder={"*Your Tripanza trip*\n• Departure details\n• Pickup location"}/></Field>
    <div className="flex items-center justify-between"><span className="text-xs text-slate-600">Optional attachment from a public HTTPS URL · up to 8 MB</span><button type="button" disabled={!!value.template} className={btn} onClick={() => onChange({ ...value, media: value.media ? undefined : { kind: "document", url: "", fileName: "itinerary.pdf" } })}>{value.media ? "Remove attachment" : "Add attachment"}</button></div>
    {value.media && <div className="grid sm:grid-cols-3 gap-3"><Field title="Attachment type"><select className={input} value={value.media.kind} onChange={e => onChange({ ...value, media: { ...value.media!, kind: e.target.value } })}><option value="document">PDF document</option><option value="image">Image</option><option value="video">MP4 video</option></select></Field><Field title="File URL"><input required type="url" className={input} value={value.media.url} onChange={e => onChange({ ...value, media: { ...value.media!, url: e.target.value } })}/></Field><Field title="Filename"><input className={input} value={value.media.fileName} onChange={e => onChange({ ...value, media: { ...value.media!, fileName: e.target.value } })}/></Field></div>}
    <div className="flex items-center justify-between"><span className="text-xs text-slate-600">Buttons · URL links or customer replies</span><button type="button" disabled={buttons.length >= 3 || !!value.template} className={btn} onClick={() => onChange({ ...value, buttons: [...buttons, { kind: "url", label: "View trip", value: "" }] })}><Plus size={14}/>Add button</button></div>
    {buttons.map((button, index) => <div key={index} className="grid grid-cols-2 sm:grid-cols-[100px_1fr_1fr_32px] gap-2"><select aria-label="Button type" className={input} value={button.kind} onChange={e => onChange({ ...value, buttons: buttons.map((item, i) => i === index ? { ...item, kind: e.target.value as Button["kind"] } : item) })}><option value="url">URL</option><option value="reply">Reply</option></select><input aria-label="Button label" required maxLength={20} className={input} value={button.label} onChange={e => onChange({ ...value, buttons: buttons.map((item, i) => i === index ? { ...item, label: e.target.value } : item) })}/><input aria-label="Button URL or reply text" required className={input} type={button.kind === "url" ? "url" : "text"} value={button.value} onChange={e => onChange({ ...value, buttons: buttons.map((item, i) => i === index ? { ...item, value: e.target.value } : item) })} placeholder={button.kind === "url" ? "https://tripanza.com/..." : "Private trip"}/><button type="button" aria-label="Remove button" className="text-slate-600 hover:text-red-300" onClick={() => onChange({ ...value, buttons: buttons.filter((_, i) => i !== index) })}><Trash2 size={16}/></button></div>)}
    {cloud && <div className="rounded-xl border border-sky-500/20 bg-sky-500/5 p-4 space-y-3"><p className="text-xs text-sky-700">Meta accounts require an approved template outside the 24-hour customer reply window. Template buttons are configured in WhatsApp Manager. Within the window, use one URL button or up to three reply buttons.</p><button type="button" disabled={!!value.template} className={btn} onClick={() => onChange({ ...value, media: undefined, buttons: [], template: value.template ? undefined : { name: "", language: "en", parameters: [] } })}>{value.template ? "Use regular message" : "Use approved template"}</button>{value.template && <div className="grid sm:grid-cols-3 gap-3"><Field title="Approved template name"><input required className={input} value={value.template.name} onChange={e => onChange({ ...value, template: { ...value.template!, name: e.target.value } })}/></Field><Field title="Language code"><input required className={input} value={value.template.language} onChange={e => onChange({ ...value, template: { ...value.template!, language: e.target.value } })}/></Field><Field title="Body parameters · one per line"><textarea className={input} value={value.template.parameters.join("\n")} onChange={e => onChange({ ...value, template: { ...value.template!, parameters: e.target.value.split("\n") } })}/></Field></div>}</div>}
  </div>;
}
export default function AutomationPanel() {
    const { user } = useAuth();
    const owner = user?.role === "super_admin";
    const [tab, setTab] = useState("scheduler"), [data, setData] = useState<Item | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
    useEffect(() => {
        const panel = new URLSearchParams(window.location.search).get("panel");
        if (panel && ["scheduler", "broadcast", "rules", "groups", "accounts", "webhooks", "buttons"].includes(panel)) setTab(panel);
    }, []);
    const polling = useRef(false);
    const [review, setReview] = useState<Item | null>(null), [reviewJobs, setReviewJobs] = useState<Item[]>([]), [reviewCursor, setReviewCursor] = useState<string | null>(null);
    const [gatewayId, setGatewayId] = useState("crm"), [name, setName] = useState(""), [recipients, setRecipients] = useState(""), [dueAt, setDueAt] = useState(""), [timezone, setTimezone] = useState("Asia/Calcutta"), [payload, setPayload] = useState<Payload>(emptyPayload);
    const [ruleId, setRuleId] = useState(""), [keyword, setKeyword] = useState(""), [match, setMatch] = useState("exact"), [context, setContext] = useState("private"), [enabled, setEnabled] = useState(false), [priority, setPriority] = useState(0), [cooldown, setCooldown] = useState(60), [whitelist, setWhitelist] = useState(""), [blacklist, setBlacklist] = useState("");
    const [accountForm, setAccountForm] = useState<Item>({ name: "", type: "qr", phoneNumberId: "", apiVersion: "v23.0", accessToken: "", appSecret: "", verifyToken: "" }), [accountEdit, setAccountEdit] = useState("");
    const [groups, setGroups] = useState<Item[]>([]), [group, setGroup] = useState<Item | null>(null), [subject, setSubject] = useState(""), [description, setDescription] = useState(""), [participants, setParticipants] = useState(""), [operation, setOperation] = useState("add"), [groupResult, setGroupResult] = useState("");
    const [webhookId, setWebhookId] = useState(""), [webhook, setWebhook] = useState<Item>({ name: "", url: "", gatewayId: "all", secret: "", enabled: false, events: ["message.received", "message.accepted", "connection"] }), [apiKeys, setApiKeys] = useState<Item[]>([]), [newToken, setNewToken] = useState("");
    const accountList: Item[] = data?.accounts || [];
    const cloud = accountList.find(item => item.id === gatewayId)?.type === "cloud";
    async function request(path: string, body?: unknown, method = body === undefined ? "GET" : "POST") {
        const response = await apiFetch("/api/automation" + path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
        const result = await response.json();
        if (!response.ok)
            throw new Error(result.error || "Action failed");
        return result;
    }
    async function load() { if (polling.current)
        return; polling.current = true; try {
        setData(await request("/overview"));
    }
    catch (error) {
        setNotice(error instanceof Error ? error.message : "Could not load automation");
    }
    finally {
        polling.current = false;
    } }
    useEffect(() => { void load(); const timer = setInterval(() => { if (!document.hidden)
        void load(); }, 5000); return () => clearInterval(timer); }, []);
    async function act(work: () => Promise<unknown>, success = "Saved") {
        setBusy(true);
        setNotice("");
        try {
            await work();
            setNotice(success);
            await load();
        }
        catch (error) {
            setNotice(error instanceof Error ? error.message : "Action failed");
        }
        finally {
            setBusy(false);
        }
    }
    const accountPicker = <Field title="WhatsApp account"><select className={input} value={gatewayId} onChange={e => { setGatewayId(e.target.value); setGroups([]); setGroup(null); }}>{accountList.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>;
    const tabs = [{ id: "scheduler", label: "Scheduler", icon: Clock }, { id: "broadcast", label: "Broadcasts", icon: Send }, { id: "rules", label: "Keyword rules", icon: Zap }, { id: "groups", label: "Groups", icon: Users }, { id: "accounts", label: "Accounts", icon: Radio }, { id: "webhooks", label: "Webhooks / n8n", icon: Link2 }, { id: "buttons", label: "Buttons", icon: MousePointer2 }];
    function exportMembers() {
        const quote = (value: unknown) => '"' + String(value || "").replace(/^[=+\-@]/, "'$&").replace(/"/g, '""') + '"';
        const csv = "jid,role\r\n" + (group?.participants || []).map((item: Item) => [quote(item.id), quote(item.admin || "member")].join(",")).join("\r\n");
        const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
        const link = document.createElement("a");
        link.href = url;
        link.download = "group-members.csv";
        link.click();
        URL.revokeObjectURL(url);
    }
    return <div className="w-full min-w-0 space-y-6 max-w-6xl mx-auto">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-widest text-brand-700 mb-2">Tripanza operations</p><h1 className="text-2xl font-semibold text-slate-900">Messaging & automation</h1><p className="text-sm text-slate-600 mt-2">Plan messages, manage accounts, and connect your travel workflows.</p></div><button className={btn} disabled={busy} onClick={() => void load()}><RefreshCw size={16}/>Refresh</button></div>
    <div className="flex gap-2 overflow-x-auto pb-2">{tabs.map(item => <button key={item.id} className={`flex items-center gap-2 whitespace-nowrap px-4 py-2.5 rounded-xl text-sm ${tab === item.id ? "bg-brand-600 text-white font-semibold" : "text-slate-600 border border-slate-200 hover:text-slate-900"}`} onClick={() => { setTab(item.id); setNotice(""); }}><item.icon size={16}/>{item.label}</button>)}</div>
    {notice && <div role="status" className="rounded-xl border border-brand-600/20 bg-brand-600/5 p-4 text-sm text-brand-700">{notice}</div>}
    {!data && <p className="text-slate-600">Loading automation…</p>}
    {(tab === "scheduler" || tab === "broadcast") && <>
      <form className={card} onSubmit={e => { e.preventDefault(); void act(async () => { await request("/campaigns", { name: name || (tab === "broadcast" ? "Trip announcement" : "Scheduled reminder"), gatewayId, recipients: split(recipients), dueAt: dueAt ? zonedIso(dueAt, timezone) : undefined, timezone, payload }); setName(""); setRecipients(""); setPayload(emptyPayload()); }, "Draft saved. Review it below and choose Start when ready."); }}>
        <h2 className="text-lg font-semibold text-slate-900">{tab === "broadcast" ? "Create a broadcast campaign" : "Schedule a message"}</h2>
        <div className="grid sm:grid-cols-2 gap-4">{accountPicker}<Field title="Name"><input className={input} maxLength={100} value={name} onChange={e => setName(e.target.value)} placeholder="Manali departure reminder"/></Field></div>
        <Field title={tab === "broadcast" ? "Recipients · international numbers or group JIDs, separated by commas/new lines" : "Recipient · international phone number or group JID"}><textarea required rows={tab === "broadcast" ? 4 : 2} className={input} value={recipients} onChange={e => setRecipients(e.target.value)} placeholder="919000000001"/></Field>
        <div className="grid sm:grid-cols-2 gap-4"><Field title="Send at · leave blank to send after Start"><input type="datetime-local" className={input} value={dueAt} onChange={e => setDueAt(e.target.value)}/></Field><Field title="Schedule timezone"><select className={input} value={timezone} onChange={e => setTimezone(e.target.value)}>{["Asia/Calcutta", "Asia/Kolkata", "Asia/Dubai", "Europe/London", "America/New_York", "UTC"].map(zone => <option key={zone}>{zone}</option>)}</select></Field></div>
        <Composer value={payload} onChange={setPayload} cloud={cloud}/>
        <p className="text-xs text-slate-500">Drafts do not send automatically. Broadcasts send one recipient at a time with 10–30 second gaps. Use recipients who expect your messages; delays do not guarantee protection from account restrictions.</p>
        <button disabled={busy} className={primary}>Save draft</button>
      </form>
      <div className={card}><h2 className="font-semibold text-slate-900">Campaigns & scheduled messages</h2>{!(data?.campaigns || []).length && <p className="text-sm text-slate-500">Your saved campaigns will appear here.</p>}{(data?.campaigns || []).map((item: Item) => <div key={item.id} className="border-t border-slate-200 pt-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium text-slate-900">{item.name}</p><p className="text-xs text-slate-600 mt-1">{item.count} recipients · {Object.entries(item.states || {}).map(([state, count]) => `${count} ${state}`).join(" · ")}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} className={btn} onClick={() => void act(async () => { const page = await request(`/jobs?campaignId=${item.id}`); setReview(item); setReviewJobs(page.jobs); setReviewCursor(page.nextCursor); }, "Campaign opened for review")}>Review</button><button disabled={busy || !item.states?.draft} className={primary} onClick={() => void act(() => request(`/campaigns/${item.id}/start`, {}), "Campaign queued")}>Start</button><button disabled={busy || !item.states?.queued} className={btn} onClick={() => void act(() => request(`/campaigns/${item.id}/pause`, {}), "Pending messages paused")}>Pause</button><button disabled={busy || !(item.states?.draft || item.states?.queued)} className={btn} onClick={() => void act(() => request(`/campaigns/${item.id}/cancel`, {}), "Pending messages canceled")}>Cancel</button></div></div>)}</div>
      {review && <div className={card}><div className="flex justify-between"><h2 className="font-semibold text-slate-900">Review: {review.name}</h2><button className={btn} onClick={() => setReview(null)}>Close review</button></div><p className="text-xs text-slate-600">{reviewJobs.length} of {review.count} recipients shown. Review recipient, account, scheduled time and content before starting.</p>{reviewJobs.map(item => { const content = JSON.parse(item.payload); return <details key={item.id} className="border-t border-slate-200 pt-3 text-sm text-slate-700"><summary className="cursor-pointer">{item.recipient} · {item.state} · {new Date(item.due_at).toLocaleString()}</summary><pre className="text-xs whitespace-pre-wrap break-all mt-3 text-slate-600">{JSON.stringify({ account: item.gateway_id, ...content }, null, 2)}</pre></details>; })}{reviewCursor && <button className={btn} disabled={busy} onClick={() => void act(async () => { const page = await request(`/jobs?campaignId=${review.id}&cursor=${reviewCursor}`); setReviewJobs([...reviewJobs, ...page.jobs]); setReviewCursor(page.nextCursor); }, "More recipients loaded")}>Load more recipients</button>}</div>}
      <div className={card}><h2 className="font-semibold text-slate-900">Recent deliveries</h2><p className="text-xs text-slate-500">Sent means accepted by WhatsApp. Unknown means a send may have completed before an error or restart; verify it before resending.</p><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-xs text-slate-500"><tr><th className="py-3">Recipient</th><th>Scheduled</th><th>Status</th><th>Details</th></tr></thead><tbody>{(data?.jobs || []).filter((item: Item) => item.recipient !== "webhook").map((item: Item) => <tr key={item.id} className="border-t border-slate-200"><td className="py-3 pr-3 text-slate-700">{item.recipient.split("@")[0]}</td><td className="pr-3 text-xs text-slate-600">{new Date(item.due_at).toLocaleString()}</td><td className="pr-3 text-brand-700">{item.state}</td><td className="text-xs text-slate-600">{item.error || item.message_id || "—"}</td></tr>)}</tbody></table></div></div>
    </>}
    {tab === "rules" && <>
      <form className={card} onSubmit={e => { e.preventDefault(); void act(async () => { await request(ruleId ? `/rules/${ruleId}` : "/rules", { name, gatewayId, keyword, match, context, enabled, priority, cooldownSeconds: cooldown, whitelist: split(whitelist), blacklist: split(blacklist), payload }, ruleId ? "PUT" : "POST"); setRuleId(""); setName(""); setKeyword(""); setPayload(emptyPayload()); setEnabled(false); }); }}>
        <h2 className="text-lg font-semibold text-slate-900">{ruleId ? "Edit keyword rule" : "New keyword rule"}</h2><p className="text-xs text-slate-600">CRM rules run before AI when the chat is available to the bot. Agent-owned, held, and AI-paused chats keep their controls. Group replies use explicitly enabled group rules.</p>
        <div className="grid sm:grid-cols-2 gap-4">{accountPicker}<Field title="Rule name"><input required className={input} value={name} onChange={e => setName(e.target.value)}/></Field><Field title="Keyword"><input required maxLength={100} className={input} value={keyword} onChange={e => setKeyword(e.target.value)}/></Field><Field title="Matching"><select className={input} value={match} onChange={e => setMatch(e.target.value)}><option value="exact">Exact match</option><option value="contains">Contains</option><option value="starts_with">Starts with</option></select></Field><Field title="Chat context"><select className={input} value={context} onChange={e => setContext(e.target.value)}><option value="private">Private chats</option><option value="group">Groups</option><option value="all">All chats</option></select></Field><Field title="Priority · higher runs first"><input type="number" className={input} value={priority} onChange={e => setPriority(Number(e.target.value))}/></Field><Field title="Cooldown in seconds · minimum 30"><input type="number" min={30} max={86400} className={input} value={cooldown} onChange={e => setCooldown(Number(e.target.value))}/></Field><Field title="Allowed numbers/groups · blank allows all"><textarea className={input} value={whitelist} onChange={e => setWhitelist(e.target.value)}/></Field><Field title="Excluded numbers/groups"><textarea className={input} value={blacklist} onChange={e => setBlacklist(e.target.value)}/></Field></div>
        <Composer value={payload} onChange={setPayload} cloud={cloud}/><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)}/>Enable this rule</label><button disabled={busy} className={primary}>Save rule</button>
      </form>
      <div className={card}><h2 className="font-semibold text-slate-900">Saved rules</h2>{(data?.rules || []).map((item: Item) => <div key={item.id} className="border-t border-slate-200 pt-4 flex justify-between gap-3"><div><p className="text-sm text-slate-900">{item.name} <span className="text-xs text-brand-700">{item.enabled ? "Enabled" : "Disabled"}</span></p><p className="text-xs text-slate-600 mt-1">{item.match} “{item.keyword}” · {item.context} · priority {item.priority}</p></div><div className="flex flex-wrap gap-2"><button className={btn} onClick={() => { setRuleId(item.id); setName(item.name); setKeyword(item.keyword); setGatewayId(item.gatewayId); setMatch(item.match); setContext(item.context); setEnabled(item.enabled); setPriority(item.priority); setCooldown(item.cooldownSeconds); setWhitelist(item.whitelist.join("\n")); setBlacklist(item.blacklist.join("\n")); setPayload(item.payload); }}>Edit</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/rules/${item.id}`, undefined, "DELETE"))}>Delete</button></div></div>)}</div>
    </>}
    {tab === "accounts" && <>
      <div className="grid md:grid-cols-2 gap-4">{accountList.map(item => <div className={card} key={item.id}><div className="flex justify-between"><h2 className="font-semibold text-slate-900">{item.name}</h2><span className="text-xs text-brand-700">{item.status}</span></div><p className="text-xs text-slate-600">{item.type === "cloud" ? "Meta Cloud API" : "QR-linked WhatsApp"}</p>{item.qr && <img src={item.qr} alt={`Pair ${item.name}`} className="rounded-xl bg-white p-3 w-48"/>}{owner && <div className="flex flex-wrap gap-2">{item.type === "qr" ? <><button disabled={busy || item.status === "connected"} className={btn} onClick={() => void act(() => request(`/accounts/${item.id}/connect`, {}), "Connection requested. Scan the QR when it appears.")}>Connect</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/accounts/${item.id}/pause`, {}), "Account paused; linked-device keys retained")}>Pause connection</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/accounts/${item.id}/logout`, {}), "Account unlinked. Connect again to pair.")}>Unlink</button></> : <button disabled={busy} className={btn} onClick={() => void act(() => request(`/accounts/${item.id}/test`, {}), "Meta credentials verified")}>Test connection</button>}{item.id.startsWith("account_") && <><button className={btn} onClick={() => { setAccountEdit(item.id); setAccountForm({ ...item, accessToken: "", appSecret: "", verifyToken: "" }); }}>Edit</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/accounts/${item.id}`, undefined, "DELETE"), "Account removed; saved auth files retained")}>Remove</button></>}</div>}{item.type === "cloud" && <p className="text-xs text-slate-500 break-all">Webhook: {typeof window !== "undefined" ? window.location.origin : ""}/api/automation/meta/webhook/{item.id}</p>}</div>)}</div>
      {owner && <form className={card} onSubmit={e => { e.preventDefault(); void act(async () => { await request(accountEdit ? `/accounts/${accountEdit}` : "/accounts", accountForm, accountEdit ? "PUT" : "POST"); setAccountEdit(""); setAccountForm({ name: "", type: "qr", apiVersion: "v23.0", accessToken: "", appSecret: "", verifyToken: "" }); }); }}><h2 className="font-semibold text-slate-900">{accountEdit ? "Edit account" : "Add WhatsApp account"}</h2><p className="text-xs text-slate-600">Existing CRM keeps the AI team inbox. Additional accounts have their own message activity, rules, campaigns and group controls. They do not reply with AI automatically. New QR accounts start only when you choose Connect; up to four extra accounts.</p><div className="grid sm:grid-cols-2 gap-4"><Field title="Name"><input required maxLength={80} className={input} value={accountForm.name} onChange={e => setAccountForm({ ...accountForm, name: e.target.value })}/></Field><Field title="Connection type"><select disabled={!!accountEdit} className={input} value={accountForm.type} onChange={e => setAccountForm({ ...accountForm, type: e.target.value })}><option value="qr">QR / Baileys</option><option value="cloud">Meta Cloud API</option></select></Field>{accountForm.type === "cloud" && ["phoneNumberId", "apiVersion", "accessToken", "appSecret", "verifyToken"].map(field => <Field title={({ phoneNumberId: "Meta phone number ID", apiVersion: "Graph API version", accessToken: "Access token", appSecret: "Meta app secret", verifyToken: "Webhook verification token" } as Record<string, string>)[field]} key={field}><input required={!accountEdit || ["phoneNumberId", "apiVersion"].includes(field)} type={["accessToken", "appSecret", "verifyToken"].includes(field) ? "password" : "text"} autoComplete="off" className={input} value={accountForm[field] || ""} placeholder={accountEdit ? "Leave secret blank to keep it" : ""} onChange={e => setAccountForm({ ...accountForm, [field]: e.target.value })}/></Field>)}</div><button disabled={busy} className={primary}>Save account</button>{accountEdit && <button type="button" className={btn} onClick={() => { setAccountEdit(""); setAccountForm({ name: "", type: "qr" }); }}>Cancel edit</button>}</form>}
      <div className={card}><h2 className="font-semibold text-slate-900">Account activity</h2>{accountPicker}<div className="max-h-96 overflow-auto space-y-3">{(data?.events || []).filter((item: Item) => item.gateway_id === gatewayId).map((item: Item) => { const details = JSON.parse(item.data); return <div key={item.id} className="border-t border-slate-200 pt-3"><p className="text-xs text-brand-700">{item.event} · {new Date(item.created_at).toLocaleString()}</p><p className="text-sm text-slate-700 whitespace-pre-wrap mt-1">{details.recipient} {details.text || details.status || details.messageId || ""}</p></div>; })}</div></div>
    </>}
    {tab === "groups" && <>
      <div className={card}><h2 className="font-semibold text-slate-900">Departure groups</h2>{accountPicker}<button disabled={busy || cloud} className={primary} onClick={() => void act(async () => setGroups(await request(`/groups/${gatewayId}/list`, {})), "Groups refreshed")}>Load groups</button>{cloud && <p className="text-xs text-slate-600">Group management is available on QR accounts.</p>}<div className="grid sm:grid-cols-2 gap-3">{groups.map(item => <button key={item.id} className="text-left rounded-xl border border-slate-200 p-4 hover:border-brand-600/40" onClick={() => void act(async () => { const result = await request(`/groups/${gatewayId}/details`, { jid: item.id }); setGroup(result); setSubject(result.subject || ""); setDescription(result.desc || ""); }, "Group opened")}><p className="text-sm text-slate-900">{item.subject || item.id}</p><p className="text-xs text-slate-500 mt-1">{item.size || item.participants?.length || 0} members</p></button>)}</div></div>
      <div className={card}><h2 className="font-semibold text-slate-900">{group ? group.subject : "Create a group"}</h2><p className="text-xs text-slate-600">WhatsApp admin permissions and participant privacy settings still apply.</p><Field title="Group name"><input className={input} value={subject} onChange={e => setSubject(e.target.value)}/></Field><Field title="Participant phone numbers"><textarea className={input} value={participants} onChange={e => setParticipants(e.target.value)}/></Field>{group ? <><Field title="Description"><textarea className={input} value={description} onChange={e => setDescription(e.target.value)}/></Field><div className="flex flex-wrap gap-2"><button disabled={busy} className={btn} onClick={() => void act(() => request(`/groups/${gatewayId}/subject`, { jid: group.id, subject }))}>Rename</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/groups/${gatewayId}/description`, { jid: group.id, description }))}>Save description</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/groups/${gatewayId}/announcement`, { jid: group.id, enabled: true }))}>Admins only</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/groups/${gatewayId}/announcement`, { jid: group.id, enabled: false }))}>All members can send</button></div><div className="flex gap-3"><select className={input} value={operation} onChange={e => setOperation(e.target.value)}>{["add", "remove", "promote", "demote"].map(value => <option key={value}>{value}</option>)}</select><button disabled={busy || !participants} className={btn} onClick={() => void act(async () => setGroupResult(JSON.stringify(await request(`/groups/${gatewayId}/participants`, { jid: group.id, participants: split(participants), operation }))), "Participant action completed; inspect the result below")}>Apply</button></div>{groupResult && <pre className="text-xs text-slate-600 overflow-auto">{groupResult}</pre>}<div className="flex flex-wrap gap-2"><button className={btn} onClick={exportMembers}><Download size={14}/>Export members</button><button className={primary} onClick={() => { setRecipients(group.id); setTab("broadcast"); }}>Message this group</button><button className={btn} onClick={() => { setGroup(null); setSubject(""); setDescription(""); }}>New group</button></div><div className="max-h-64 overflow-auto text-xs text-slate-600 space-y-2">{(group.participants || []).map((item: Item) => <p key={item.id}>{item.id} · {item.admin || "member"}</p>)}</div></> : <button disabled={busy || cloud || !subject || !participants} className={primary} onClick={() => void act(async () => { const result = await request(`/groups/${gatewayId}/create`, { subject, participants: split(participants) }); setGroup(result); }, "Group created")}>Create group</button>}</div>
    </>}
    {tab === "webhooks" && <>
      {owner && <form className={card} onSubmit={e => { e.preventDefault(); void act(async () => { await request(webhookId ? `/webhooks/${webhookId}` : "/webhooks", webhook, webhookId ? "PUT" : "POST"); setWebhookId(""); setWebhook({ name: "", url: "", gatewayId: "all", secret: "", enabled: false, events: ["message.received", "message.accepted", "connection"] }); }); }}><h2 className="font-semibold text-slate-900">{webhookId ? "Edit webhook" : "Connect a webhook / n8n workflow"}</h2><p className="text-xs text-slate-600">Use an HTTPS n8n Webhook node. Events contain an ID, type, account and data. Deliveries retry up to five times; use the event ID to avoid duplicate workflow actions.</p><div className="grid sm:grid-cols-2 gap-4"><Field title="Name"><input required className={input} value={webhook.name} onChange={e => setWebhook({ ...webhook, name: e.target.value })}/></Field><Field title="Public HTTPS webhook URL"><input required type="url" className={input} value={webhook.url} onChange={e => setWebhook({ ...webhook, url: e.target.value })}/></Field><Field title="Signing secret"><input required={!webhookId} type="password" autoComplete="off" className={input} value={webhook.secret} onChange={e => setWebhook({ ...webhook, secret: e.target.value })} placeholder={webhookId ? "Leave blank to keep saved secret" : ""}/></Field><Field title="Account"><select className={input} value={webhook.gatewayId} onChange={e => setWebhook({ ...webhook, gatewayId: e.target.value })}><option value="all">All accounts</option>{accountList.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><div className="flex flex-wrap gap-4">{["message.received", "message.accepted", "message.status", "connection", "group.updated"].map(event => <label key={event} className="text-xs text-slate-600 flex items-center gap-2"><input type="checkbox" checked={webhook.events.includes(event)} onChange={e => setWebhook({ ...webhook, events: e.target.checked ? [...webhook.events, event] : webhook.events.filter((value: string) => value !== event) })}/>{event}</label>)}</div><label className="text-sm text-slate-700 flex items-center gap-3"><input type="checkbox" checked={webhook.enabled} onChange={e => setWebhook({ ...webhook, enabled: e.target.checked })}/>Enable deliveries</label><button disabled={busy} className={primary}>Save webhook</button></form>}
      <div className={card}>{(data?.webhooks || []).map((item: Item) => <div key={item.id} className="border-t border-slate-200 pt-4 flex justify-between gap-4"><div><p className="text-slate-900 text-sm">{item.name} · {item.enabled ? "Enabled" : "Disabled"}</p><p className="text-xs text-slate-500 break-all">{item.url}</p></div>{owner && <div className="flex flex-wrap gap-2"><button className={btn} onClick={() => { setWebhookId(item.id); setWebhook({ ...item, secret: "" }); }}>Edit</button><button disabled={busy} className={btn} onClick={() => void act(() => request(`/webhooks/${item.id}`, undefined, "DELETE"))}>Delete</button></div>}</div>)}</div>
      {owner && <div className={card}><h2 className="font-semibold text-slate-900">Automation API keys</h2><p className="text-xs text-slate-600">Use an n8n HTTP Request node with the X-API-Key header. These keys can manage drafts, campaigns, rules and groups; account credentials and webhook secrets require your owner login.</p><div className="flex flex-wrap gap-2"><input aria-label="API key name" className={input} value={name} onChange={e => setName(e.target.value)} placeholder="n8n trip workflows"/><button disabled={busy || !name} className={primary} onClick={() => void act(async () => { const result = await request("/api-keys", { name }); setNewToken(result.token); setApiKeys(await request("/api-keys")); }, "Copy the new key now. It is shown only once.")}>Generate</button><button className={btn} onClick={() => void act(async () => setApiKeys(await request("/api-keys")), "API keys loaded")}>List</button></div>{newToken && <div className="rounded-xl bg-slate-50 p-4 space-y-2"><code className="text-xs text-brand-700 break-all">{newToken}</code><button className={btn} onClick={() => setNewToken("")}>Hide key</button></div>}{apiKeys.map(item => <div key={item.id} className="flex justify-between text-sm text-slate-600"><span>{item.name}</span><button disabled={busy} className={btn} onClick={() => void act(async () => { await request(`/api-keys/${item.id}`, undefined, "DELETE"); setApiKeys(await request("/api-keys")); }, "API key revoked")}>Revoke</button></div>)}<pre className="text-xs text-slate-600 overflow-auto bg-slate-50 rounded-xl p-4">{`POST /api/automation/campaigns\nX-API-Key: YOUR_KEY\n\n{ "gatewayId": "crm", "recipients": ["919000000001"],\n  "name": "Trip reminder", "payload": { "text": "Your departure details…" } }\n\nPOST /api/automation/campaigns/CAMPAIGN_ID/start`}</pre></div>}
      <div className={card}><h2 className="font-semibold text-slate-900">Webhook delivery log</h2>{(data?.jobs || []).filter((item: Item) => item.recipient === "webhook").map((item: Item) => <p key={item.id} className="text-xs text-slate-600">{new Date(item.updated_at).toLocaleString()} · {item.state} · {item.attempts} attempts · {item.error || ""}</p>)}</div>
    </>}
    {tab === "buttons" && <div className={card}><h2 className="font-semibold text-slate-900">WhatsApp call-to-action buttons</h2><p className="text-sm text-slate-600">Build URL and reply buttons in the message composer or keyword rules. Link mode keeps messages readable in every client. Experimental Baileys mode sends the readable message followed by an interactive card; some clients may not show that card.</p><div className="grid md:grid-cols-2 gap-4">{[{ mode: "links", title: "Clickable links & reply prompts", body: "Default. Customers open URLs or type the suggested response." }, { mode: "experimental", title: "Experimental QR buttons", body: "Adds URL and quick-reply cards. AI replies containing URLs also receive a URL card." }].map(item => <button key={item.mode} disabled={busy} className={`rounded-xl border p-5 text-left ${data?.buttons?.mode === item.mode ? "border-brand-600 bg-brand-600/5" : "border-slate-300"}`} onClick={() => void act(() => request("/buttons", { mode: item.mode }, "PUT"), "Button mode saved")}><p className="text-sm font-semibold text-slate-900">{item.title}</p><p className="text-xs text-slate-600 mt-2">{item.body}</p></button>)}</div><p className="text-xs text-sky-700">Meta accounts use officially supported reply/URL buttons inside the customer reply window. For website/call buttons outside that window, create approved templates in WhatsApp Manager and choose them in your campaign.</p></div>}
  </div>;
}
